[server]
host = "127.0.0.1"
port = 8080

[database]
url = "sqlite:./rusktop.db?mode=rwc"

[log]
env = "prod"
level = "debug"

[log.file]
path = "logs/rusktop.log"
max_size_mb = 10
max_backups = 5
max_age_days = 7
compress = false
