.PHONY: help run.web run.ui build.web build.ui lint-proto fmt-proto openapi check-openapi-tools ensure-openapi check-proto-workflow

GREEN := \033[0;32m
CYAN := \033[0;36m
YELLOW := \033[0;33m
RESET := \033[0m

ROOT_DIR := $(shell pwd)
API_DIR := $(ROOT_DIR)/api
PROTO_DIR := $(API_DIR)/protos
OPENAPI_FILE := $(API_DIR)/openapi/v1/openapi.yaml

.DEFAULT_GOAL := help

help:
	@echo ""
	@echo "$(CYAN)Rusktop Makefile$(RESET)"
	@echo "$(CYAN)================$(RESET)"
	@echo ""
	@echo "Usage:"
	@echo "  make [target]"
	@echo ""
	@echo "$(YELLOW)Run Commands:$(RESET)"
	@echo "  $(GREEN)run.web$(RESET)     - Start web server (REST API)"
	@echo "  $(GREEN)run.ui$(RESET)      - Start UI application (GPUI)"
	@echo ""
	@echo "$(YELLOW)Build Commands:$(RESET)"
	@echo "  $(GREEN)build.web$(RESET)   - Build web-only binary (no UI deps)"
	@echo "  $(GREEN)build.ui$(RESET)    - Build full binary (UI + Web)"
	@echo ""
	@echo "$(YELLOW)Proto Tools:$(RESET)"
	@echo "  $(GREEN)openapi$(RESET)     - Generate OpenAPI documentation"
	@echo "  $(GREEN)check-proto-workflow$(RESET) - Check proto workflow sync points"
	@echo "  $(GREEN)lint-proto$(RESET)  - Lint protobuf files"
	@echo "  $(GREEN)fmt-proto$(RESET)   - Format protobuf files"
	@echo ""
	@echo "$(YELLOW)Note:$(RESET) Proto code is auto-generated by build.rs (no manual 'make gen' needed)"
	@echo ""

run.web: ensure-openapi
	@echo "$(CYAN)Starting Web Server...$(RESET)"
	@cargo run --no-default-features -- web

run.ui:
	@echo "$(CYAN)Starting UI Application...$(RESET)"
	@cargo run

build.web:
	@echo "$(CYAN)Building web-only binary...$(RESET)"
	@cargo build -p rusktop-app --no-default-features --release
	@echo "$(GREEN)✓ Binary: target/release/rusktop-app$(RESET)"

build.ui:
	@echo "$(CYAN)Building full binary...$(RESET)"
	@cargo build -p rusktop-app --release
	@echo "$(GREEN)✓ Binary: target/release/rusktop-app$(RESET)"

check-openapi-tools:
	@if ! command -v buf >/dev/null 2>&1; then \
		echo "$(YELLOW)Missing required tool: buf$(RESET)"; \
		echo "Install: brew install bufbuild/buf/buf"; \
		echo "Or: https://buf.build/docs/installation"; \
		exit 1; \
	fi
	@if ! command -v protoc-gen-openapi >/dev/null 2>&1; then \
		echo "$(YELLOW)Missing required plugin: protoc-gen-openapi$(RESET)"; \
		echo "Install: go install github.com/google/gnostic/cmd/protoc-gen-openapi@latest"; \
		echo "Ensure plugin is in PATH (example): export PATH=$$PATH:$$(go env GOPATH)/bin"; \
		exit 1; \
	fi

openapi: check-openapi-tools
	@echo "$(CYAN)Generating OpenAPI documentation...$(RESET)"
	@cd $(API_DIR) && buf generate --template buf.openapi.gen.yaml
	@echo "$(GREEN)✓ OpenAPI documentation generated at api/openapi/v1/openapi.yaml$(RESET)"

ensure-openapi: check-openapi-tools
	@if [ ! -f "$(OPENAPI_FILE)" ] || \
	   [ -n "$$(find "$(PROTO_DIR)" -name "*.proto" -newer "$(OPENAPI_FILE)" -print -quit)" ] || \
	   [ "$(API_DIR)/buf.openapi.gen.yaml" -nt "$(OPENAPI_FILE)" ]; then \
		echo "$(CYAN)OpenAPI is missing or stale, regenerating...$(RESET)"; \
		$(MAKE) openapi; \
	fi

check-proto-workflow:
	@./scripts/check-proto-workflow.sh

lint-proto:
	@echo "$(CYAN)Linting protobuf files...$(RESET)"
	@cd $(PROTO_DIR) && buf lint
	@echo "$(GREEN)✓ Proto lint complete$(RESET)"

fmt-proto:
	@echo "$(CYAN)Formatting protobuf files...$(RESET)"
	@cd $(PROTO_DIR) && buf format -w
	@echo "$(GREEN)✓ Proto files formatted$(RESET)"

new-migration:
	@if [ -z "$(name)" ]; then \
		echo "$(YELLOW)Usage: make new-migration name=<description>$(RESET)"; \
		echo ""; \
		echo "Example: make new-migration name=add_email_to_users"; \
		exit 1; \
	fi
	@./scripts/new-migration.sh $(name)
