[package]
name = "rusktop-app"
version.workspace = true
edition.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(feature, values("ui"))'] }

[features]
default = ["ui"]
ui = ["dep:rusktop-ui", "dep:gpui", "dep:gpui-component"]

[dependencies]
rusktop-core.workspace = true
rusktop-ui = { workspace = true, optional = true }
rusktop-web.workspace = true
gpui = { workspace = true, optional = true }
gpui-component = { workspace = true, optional = true }
clap.workspace = true
konfig.workspace = true
lug.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
